src/OrchardCore.Modules/OrchardCore.Deployment.Remote/Models/RemoteClient.cs
namespace OrchardCore.Deployment.Remote.Models
{
    public class RemoteClient
    {
        public string Id { get; set; }
        public string ClientName { get; set; }
        public byte[] ProtectedApiKey { get; set; }
    }
}

src/OrchardCore.Modules/OrchardCore.Deployment.Remote/Controllers/ImportRemoteInstanceController.cs
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;
using OrchardCore.Deployment.Remote.Services;
using OrchardCore.Deployment.Remote.ViewModels;
using OrchardCore.Deployment.Services;

namespace OrchardCore.Deployment.Remote.Controllers
{
    public class ImportRemoteInstanceController : Controller
    {
        private readonly RemoteClientService _remoteClientService;
        private readonly IDeploymentManager _deploymentManager;
        private readonly IDataProtector _dataProtector;

        public ImportRemoteInstanceController(
            IDataProtectionProvider dataProtectionProvider,
            RemoteClientService remoteClientService,
            IDeploymentManager deploymentManager)
        {
            _deploymentManager = deploymentManager;
            _remoteClientService = remoteClientService;
            _dataProtector = dataProtectionProvider.CreateProtector("OrchardCore.Deployment").ToTimeLimitedDataProtector();
        }

        /// <remarks>
        /// We ignore the AFT as the service is called from external applications (they can't have valid ones) and
        /// we use a private API key to secure its calls.
        /// </remarks>
        [HttpPost]
        [IgnoreAntiforgeryToken]
        public async Task<IActionResult> Import(ImportViewModel model)
        {
            var remoteClientList = await _remoteClientService.GetRemoteClientListAsync();

            var remoteClient = remoteClientList.RemoteClients.FirstOrDefault(x => x.ClientName == model.ClientName);

            if (remoteClient == null)
            {
                return StatusCode((int)HttpStatusCode.BadRequest, "The remote client was not provided");
            }

            var apiKey = Encoding.UTF8.GetString(_dataProtector.Unprotect(remoteClient.ProtectedApiKey));

            if (model.ApiKey != apiKey || model.ClientName != remoteClient.ClientName)
            {
                return StatusCode((int)HttpStatusCode.BadRequest, "The Api Key was not recognized");
            }

            // Create a temporary filename to save the archive
            var tempArchiveName = Path.GetTempFileName() + ".zip";

            // Create a temporary folder to extract the archive to
            var tempArchiveFolder = PathExtensions.Combine(Path.GetTempPath(), Path.GetRandomFileName());

            try
            {
                using (var fs = System.IO.File.Create(tempArchiveName))
                {
                    await model.Content.CopyToAsync(fs);
                }

                ZipFile.ExtractToDirectory(tempArchiveName, tempArchiveFolder);

                await _deploymentManager.ImportDeploymentPackageAsync(new PhysicalFileProvider(tempArchiveFolder));
            }
            finally
            {
                if (System.IO.File.Exists(tempArchiveName))
                {
                    System.IO.File.Delete(tempArchiveName);
                }

                if (Directory.Exists(tempArchiveFolder))
                {
                    Directory.Delete(tempArchiveFolder, true);
                }
            }

            return Ok();
        }
    }
}

src/OrchardCore.Modules/OrchardCore.Deployment.Remote/Controllers/RemoteClientController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Localization;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.AspNetCore.Routing;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Options;
using OrchardCore.Admin;
using OrchardCore.Deployment.Remote.Services;
using OrchardCore.Deployment.Remote.ViewModels;
using OrchardCore.DisplayManagement;
using OrchardCore.DisplayManagement.Notify;
using OrchardCore.Navigation;
using OrchardCore.Routing;

namespace OrchardCore.Deployment.Remote.Controllers
{
    [Admin("Deployment/RemoteClient/{action}/{id?}", "DeploymentRemoteClient{action}")]
    public class RemoteClientController : Controller
    {
        private const string _optionsSearch = "Options.Search";

        private readonly IDataProtector _dataProtector;
        private readonly IAuthorizationService _authorizationService;
        private readonly PagerOptions _pagerOptions;
        private readonly IShapeFactory _shapeFactory;
        private readonly RemoteClientService _remoteClientService;
        private readonly INotifier _notifier;

        protected readonly IStringLocalizer S;
        protected readonly IHtmlLocalizer H;

        public RemoteClientController(
            IDataProtectionProvider dataProtectionProvider,
            RemoteClientService remoteClientService,
            IAuthorizationService authorizationService,
            IOptions<PagerOptions> pagerOptions,
            IShapeFactory shapeFactory,
            IStringLocalizer<RemoteClientController> stringLocalizer,
            IHtmlLocalizer<RemoteClientController> htmlLocalizer,
            INotifier notifier
            )
        {
            _authorizationService = authorizationService;
            _pagerOptions = pagerOptions.Value;
            _shapeFactory = shapeFactory;
            S = stringLocalizer;
            H = htmlLocalizer;
            _notifier = notifier;
            _remoteClientService = remoteClientService;
            _dataProtector = dataProtectionProvider.CreateProtector("OrchardCore.Deployment").ToTimeLimitedDataProtector();
        }

        public async Task<IActionResult> Index(ContentOptions options, PagerParameters pagerParameters)
        {
            if (!await _authorizationService.AuthorizeAsync(User, Permissions.ManageRemoteClients))
            {
                return Forbid();
            }

            var pager = new Pager(pagerParameters, _pagerOptions.GetPageSize());

            var remoteClients = (await _remoteClientService.GetRemoteClientListAsync()).RemoteClients;

            if (!string.IsNullOrWhiteSpace(options.Search))
            {
                remoteClients = remoteClients.Where(x => x.ClientName.Contains(options.Search, StringComparison.OrdinalIgnoreCase)).ToList();
            }

            var count = remoteClients.Count;

            var startIndex = pager.GetStartIndex();
            var pageSize = pager.PageSize;

            // Maintain previous route data when generating page links.
            var routeData = new RouteData();

            if (!string.IsNullOrEmpty(options.Search))
            {
                routeData.Values.TryAdd(_optionsSearch, options.Search);
            }

            var pagerShape = await _shapeFactory.PagerAsync(pager, count, routeData);

            var model = new RemoteClientIndexViewModel
            {
                RemoteClients = remoteClients,
                Pager = pagerShape,
                Options = options
            };

            model.Options.ContentsBulkAction =
            [
                new SelectListItem(S["Delete"], nameof(ContentsBulkAction.Remove)),
            ];

            return View(model);
        }

        [HttpPost, ActionName(nameof(Index))]
        [FormValueRequired("submit.Filter")]
        public ActionResult IndexFilterPOST(RemoteClientIndexViewModel model)
            => RedirectToAction(nameof(Index), new RouteValueDictionary
            {
                { _optionsSearch, model.Options.Search }
            });

        public async Task<IActionResult> Create()
        {
            if (!await _authorizationService.AuthorizeAsync(User, Permissions.ManageRemoteClients))
            {
                return Forbid();
            }

            var model = new EditRemoteClientViewModel();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(EditRemoteClientViewModel model)
        {
            if (!await _authorizationService.AuthorizeAsync(User, Permissions.ManageRemoteClients))
            {
                return Forbid();
            }

            if (ModelState.IsValid)
            {
                ValidateViewModel(model);
            }

            if (ModelState.IsValid)
            {
                await _remoteClientService.CreateRemoteClientAsync(model.ClientName, model.ApiKey);

                await _notifier.SuccessAsync(H["Remote client created successfully."]);
                return RedirectToAction(nameof(Index));
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            if (!await _authorizationService.AuthorizeAsync(User, Permissions.ManageRemoteClients))
            {
                return Forbid();
            }

            var remoteClient = await _remoteClientService.GetRemoteClientAsync(id);

            if (remoteClient == null)
            {
                return NotFound();
            }

            var model = new EditRemoteClientViewModel
            {
                Id = remoteClient.Id,
                ClientName = remoteClient.ClientName,
                ApiKey = Encoding.UTF8.GetString(_dataProtector.Unprotect(remoteClient.ProtectedApiKey)),
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(EditRemoteClientViewModel model)
        {
            if (!await _authorizationService.AuthorizeAsync(User, Permissions.ManageRemoteClients))
            {
                return Forbid();
            }

            var remoteClient = await _remoteClientService.GetRemoteClientAsync(model.Id);

            if (remoteClient == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                ValidateViewModel(model);
            }

            if (ModelState.IsValid)
            {
                await _remoteClientService.TryUpdateRemoteClient(model.Id, model.ClientName, model.ApiKey);

                await _notifier.SuccessAsync(H["Remote client updated successfully."]);

                return RedirectToAction(nameof(Index));
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            if (!await _authorizationService.AuthorizeAsync(User, Permissions.ManageRemoteClients))
            {
                return Forbid();
            }

            var remoteClient = await _remoteClientService.GetRemoteClientAsync(id);

            if (remoteClient == null)
            {
                return NotFound();
            }

            await _remoteClientService.DeleteRemoteClientAsync(id);

            await _notifier.SuccessAsync(H["Remote client deleted successfully."]);

            return RedirectToAction(nameof(Index));
        }

        [HttpPost, ActionName("Index")]
        [FormValueRequired("submit.BulkAction")]
        public async Task<ActionResult> IndexPost(ViewModels.ContentOptions options, IEnumerable<string> itemIds)
        {
            if (!await _authorizationService.AuthorizeAsync(User, Permissions.ManageRemoteInstances))
            {
                return Forbid();
            }

            if (itemIds?.Count() > 0)
            {
                var remoteClients = (await _remoteClientService.GetRemoteClientListAsync()).RemoteClients;
                var checkedContentItems = remoteClients.Where(x => itemIds.Contains(x.Id)).ToList();

                switch (options.BulkAction)
                {
                    case ContentsBulkAction.None:
                        break;
                    case ContentsBulkAction.Remove:
                        foreach (var item in checkedContentItems)
                        {
                            await _remoteClientService.DeleteRemoteClientAsync(item.Id);
                        }
                        await _notifier.SuccessAsync(H["Remote clients successfully removed."]);
                        break;
                    default:
                        return BadRequest();
                }
            }

            return RedirectToAction("Index");
        }

        private void ValidateViewModel(EditRemoteClientViewModel model)
        {
            if (string.IsNullOrWhiteSpace(model.ClientName))
            {
                ModelState.AddModelError(nameof(EditRemoteClientViewModel.ClientName), S["The client name is mandatory."]);
            }

            if (string.IsNullOrWhiteSpace(model.ApiKey))
            {
                ModelState.AddModelError(nameof(EditRemoteClientViewModel.ApiKey), S["The api key is mandatory."]);
            }
        }
    }
}

src/OrchardCore.Modules/OrchardCore.Deployment.Remote/Views/RemoteClient/Create.cshtml
@model EditRemoteClientViewModel

<div asp-validation-summary="ModelOnly"></div>
<form asp-action="Create" method="post" class="no-multisubmit">

    <div class="mb-3" asp-validation-class-for="ClientName">
        <label asp-for="ClientName" class="form-label">@T["Client Name"]</label>
        <input asp-for="ClientName" class="form-control" />
        <span asp-validation-for="ClientName" class="text-danger"></span>
    </div>

    <div class="mb-3" asp-validation-class-for="ApiKey">
        <label asp-for="ApiKey" class="form-label">@T["Api Key"]</label>
        <input asp-for="ApiKey" type="password" class="form-control" />
        <span asp-validation-for="ApiKey" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <button class="btn btn-primary create" type="submit">@T["Create"]</button>
        <a class="btn btn-secondary cancel" role="button" asp-route-action="Index">@T["Cancel"]</a>
    </div>
</form>

src/OrchardCore.Modules/OrchardCore.Deployment.Remote/Views/RemoteClient/Edit.cshtml
@model EditRemoteClientViewModel

<zone Name="Title"><h1>@RenderTitleSegments(T["Edit Remote Client"])</h1></zone>

<div asp-validation-summary="ModelOnly"></div>
<form asp-action="Edit" method="post" class="no-multisubmit">
    <input type="hidden" asp-for="Id" />

    <div class="mb-3" asp-validation-class-for="ClientName">
        <label asp-for="ClientName" class="form-label">@T["Client Name"]</label>
        <input asp-for="ClientName" class="form-control" />
        <span asp-validation-for="ClientName" class="text-danger"></span>
    </div>

    <div class="mb-3" asp-validation-class-for="ApiKey">
        <label asp-for="ApiKey" class="form-label">@T["Api Key"]</label>
        <input asp-for="ApiKey" type="password" class="form-control" value="@Model.ApiKey" />
        <span asp-validation-for="ApiKey" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <button class="btn btn-primary save" type="submit">@T["Save"]</button>
        <a class="btn btn-secondary cancel" role="button" asp-route-action="Index">@T["Cancel"]</a>
    </div>
</form>

src/OrchardCore.Modules/OrchardCore.Deployment.Remote/Views/RemoteClient/Index.cshtml
@model RemoteClientIndexViewModel
@{
    int startIndex = (Model.Pager.Page - 1) * (Model.Pager.PageSize) + 1;
    int endIndex = startIndex + Model.RemoteClients.Count() - 1;
}

<zone Name="Title"><h1>@RenderTitleSegments(T["Remote Clients"])</h1></zone>

<div class="alert alert-info text-break" role="alert">
    @T["Url to use from client instances: <b>{0}</b>", Url.Action("Import", "ImportRemoteInstance", null, Context.Request.Scheme)]
</div>

@* the form is necessary to generate and antiforgery token for the delete action *@
<form asp-action="Index">
    <input type="submit" name="submit.Filter" id="submitFilter" class="visually-hidden" />
    <input asp-for="Options.BulkAction" type="hidden" />
    <input type="submit" name="submit.BulkAction" class="visually-hidden" />

    <div class="card text-bg-theme mb-3 position-sticky action-bar">
        <div class="card-body">
            <div class="row gx-3">
                <div class="col">
                    <div class="has-search">
                        <i class="fa-solid fa-search form-control-feedback" aria-hidden="true"></i>
                        <input asp-for="Options.Search" class="form-control" placeholder="@T["Search"]" type="search" autofocus />
                    </div>
                </div>
                <div class="col-auto">
                    <a asp-route-action="Create" class="btn btn-secondary create" role="button">@T["Add Remote Client"]</a>
                </div>
            </div>
        </div>
    </div>
    <ul class="list-group with-checkbox">
        @if (Model.RemoteClients.Count > 0)
        {
            <li class="list-group-item text-bg-theme">
                <div class="row gx-3">
                    <div class="col">
                        <div class="text-nowrap">
                            <div class="form-check my-1">
                                <input type="checkbox" class="form-check-input" id="select-all">
                                <label class="form-check-label" for="select-all" id="select-all-label" title="@T["Select All"]"></label>
                                <label id="items" for="select-all">@T.Plural(Model.RemoteClients.Count(), "1 item", "{0} items")<span class="text-muted" title="@T["Items {0} to {1}", startIndex, endIndex]">@T.Plural((int)Model.Pager.TotalItemCount, " / {0} item in total", " / {0} items in total")</span></label>
                                <label id="selected-items" class="text-muted" for="select-all"></label>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <div style="display:none" id="actions">
                            <div class="dropdown">
                                <button class="btn btn-sm btn-light dropdown-toggle" type="button" id="bulk-action-menu-button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    @T["Actions"]
                                </button>
                                <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="bulk-action-menu-button">
                                    @foreach (var item in Model.Options.ContentsBulkAction)
                                    {
                                        <li><a class="dropdown-item" href="javascript:void(0)" data-action="@item.Value" data-title="@T["Bulk Action"]" data-message="@T["Are you sure you want to {0} these items?", @item.Text.ToLower()]">@item.Text</a></li>
                                    }
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
            @foreach (var entry in Model.RemoteClients)
            {
                <li class="list-group-item">
                    <div class="form-check float-start">
                        <input type="checkbox" class="form-check-input" value="@entry.Id" name="itemIds" id="itemIds-@entry.Id">
                        <label class="form-check-label" for="itemIds-@entry.Id">&nbsp;</label>
                    </div>
                    <div class="w-100">
                        <div class="float-end">
                            <a asp-action="Edit" asp-route-id="@entry.Id" class="btn btn-primary btn-sm">@T["Edit"]</a>
                            <a asp-action="Delete" asp-route-id="@entry.Id" class="btn btn-danger btn-sm" data-url-af="RemoveUrl UnsafeUrl">@T["Delete"]</a>
                        </div>
                        <h5>@entry.ClientName</h5>
                    </div>
                </li>
            }
        }
        else
        {
            <li class="list-group-item">
                <div class="alert alert-info mb-0" role="alert">
                    @T["<strong>Nothing here!</strong> There are no remote clients for the moment."]
                </div>
            </li>
        }
    </ul>
</form>

@await DisplayAsync(Model.Pager)

<script at="Foot">
    $(function () {
        var actions = $("#actions");
        var items = $("#items");
        var filters = $(".filter");
        var selectAllCtrl = $("#select-all");
        var selectedItems = $("#selected-items");
        var itemsCheckboxes = $(":checkbox[name='itemIds']");

        function displayActionsOrFilters() {
            if ($(":checkbox[name='itemIds']:checked").length > 1) {
                actions.show();
                filters.hide();
                selectedItems.show();
                items.hide();
            }
            else {
                actions.hide();
                filters.show();
                selectedItems.hide();
                items.show();
            }
        }

        $(".dropdown-menu .dropdown-item").filter(function () {
            return $(this).data("action");
        }).on("click", function () {
            if ($(":checkbox[name='itemIds']:checked").length > 1) {
                var $this = $(this);
                confirmDialog({
                    ...$this.data(), callback: function (r) {
                        if (r) {
                            $("[name='Options.BulkAction']").val($this.data("action"));
                            $("[name='submit.BulkAction']").click();
                        }
                    }
                });
            }
        });

        selectAllCtrl.click(function () {
            itemsCheckboxes.not(this).prop("checked", this.checked);
            selectedItems.text($(":checkbox[name='itemIds']:checked").length + ' @T["selected"]');
            displayActionsOrFilters();
        });

        itemsCheckboxes.on("click", function () {
            var itemsCount = $(":checkbox[name='itemIds']").length;
            var selectedItemsCount = $(":checkbox[name='itemIds']:checked").length;

            selectAllCtrl.prop("checked", selectedItemsCount == itemsCount);
            selectAllCtrl.prop("indeterminate", selectedItemsCount > 0 && selectedItemsCount < itemsCount);

            selectedItems.text(selectedItemsCount + ' @T["selected"]');
            displayActionsOrFilters();
        });
    })
</script>